site_name: Modelo de TIGHT BINDING de ocupación simple con potencial definido

theme:
  name: "material"
  features: 
    - content.code.copy

nav:
  - index.md
  - explanation.md
  - tutorials.md
  - parallel.md
  - results.md
  - reference.md

plugins:
  - mkdocstrings:

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
